import type { Metadata } from 'next';

import StoreProvider from './StoreProvider';

import { Footer } from '@/modules';
import { Header } from '@/modules';

import '../styles/globals.css';

import ToastProvider from './GlobalProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
  }) {
  
  const isDev = process.env.NODE_ENV === 'development';
  
  return (
    <StoreProvider>
      <html lang="en" suppressHydrationWarning={isDev}>
        {/* <body className="font-lato font-normal"> */}
        <body>
          <ToastProvider>
            <Header />
            <main>{children}</main>
            <Footer />
          </ToastProvider>
        </body>
      </html>
    </StoreProvider>
  );
}
